Merge to main
Fugazante/rising-cloud-deployment pull request #2
Opened 2024-01-12 10:01 UTC by cobreyplomo

- Add echos to every step in the action
- Add HowTo documentation

2024-01-17 19:43 UTC, minirulo requested changes
Check typos everywhere, mainly focusing on logging and documentation:
- Things like "Deploying in Rising Cloud" -> "Deploying **_to_** Rising Cloud"
- Ortographic errors: "has been develop" -> "has been **_developed_**"
- Small typos: "Deploy Web Serive" -> "Deploy Web **_Service_**"
- And so on.

Just read everything carefully.

2024-01-17 19:43 UTC, minirulo commented on action.yml
>      - name: Install ca-certificates
This step is doing several things. Rename it to englobe them all or split into different steps

2024-01-18 20:00 UTC, minirulo requested changes

2024-01-18 20:00 UTC, minirulo commented on action.yml
> +    - name: Check if Password or User Info Empty
_"Validate user inputs"_ sounds more interesting

2024-01-18 20:00 UTC, minirulo commented on README.md
> +**risincloud.yaml**. If it is not the case, it is possible to configure the path and the file name using the following optional
Have you read carefully? The default document that the action is looking into is _**risingcloud.yaml**_

2024-01-18 20:00 UTC, minirulo commented on action.yml
>      - name: Login Rising Cloud
Loing _"to"_

2024-01-18 20:00 UTC, minirulo commented on action.yml
> +    - name: Installing Rising Cloud CLI
For best practices regarding naming convention, steps should be called by imperative actions. In this case _"Install"_ would be more appropiate

2024-01-18 20:08 UTC, cobreyplomo commented on action.yml
> +    - name: Check if Password or User Info Empty
done

2024-01-18 20:09 UTC, cobreyplomo commented on README.md
> +**risincloud.yaml**. If it is not the case, it is possible to configure the path and the file name using the following optional
done

2024-01-21 17:46 UTC, minirulo approved these changes

2024-01-21 18:41 UTC, merged